name: Test site for publicly konwn js vulnerabilities

on:
  push:
    branches: [main]

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Test for public javascript library vulnerabilities
        uses: lirantal/is-website-vulnerable@mater
        with:
          scan-url: "https://yceffort.kr"
